[package]
name = "sandwitch"
version = "0.1.0"
edition = "2021"

[features]
default = [
  "bsc",
]

bsc = [
  "pancake_swap",
]
pancake_swap = []

[dependencies]
anyhow = "1"
futures = "0.3"
itertools = "0.10"
lazy_static = "1.4"
metrics = "0.20"
pin-project = "1"
thiserror = "1"
tokio-util = "0.7"
toml = "0.5"
tracing = "0.1"

[dependencies.clap]
version = "4.0"
features = ["derive"]

[dependencies.ethers]
version = "1"
default-features = false
features = [
  "abigen",
  "rustls",
  "ws",
]

[dependencies.metrics-exporter-prometheus]
version = "0.11"
default-features = false
features = ["http-listener"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
default-features = false
features = [
  "fs",
  "time",
  "rt-multi-thread",
]

[dependencies.tokio-stream]
version = "0.1"
features = [
	"fs",
	"sync",
]

[dependencies.tracing-subscriber]
version = "0.3"
features = ["env-filter"]

[dependencies.url]
version = "2.2"
features = ["serde"]


[build-dependencies.ethers-contract]
version = "1"
default-features = false
features = ["abigen"]
