[package]
name = "sandwitch"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-broadcast = "0.4"
futures = "0.3"
hex = "0.4"
itertools = "0.10"
lazy_static = "1.4"
metrics = "0.20"
tokio-util = "0.7"
toml = "0.5"
tracing = "0.1"

[dependencies.clap]
version = "3.2"
features = ["derive"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.metrics-exporter-prometheus]
version = "0.11"
default-features = false
features = ["http-listener"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.tokio-stream]
version = "0.1"
features = ["sync"]

[dependencies.tracing-subscriber]
version = "0.3"
features = ["env-filter"]

[dependencies.web3]
version = "0.18"
default-features = false
features = [
	"http",
	"http-rustls-tls",
	"ws-tokio",
	"ws-tls-tokio",
]
