[package]
name = "sandwitch"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-broadcast = "0.4"
futures = "0.3"
hex = "0.4"
itertools = "0.10"
lazy_static = "1.4"
toml = "0.5"

[dependencies.clap]
version = "3.2"
features = ["derive"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.tokio-stream]
version = "0.1"
features = ["sync"]

[dependencies.web3]
version = "0.18"
default-features = false
features = [
	"http",
	"http-rustls-tls",
	"ws-tokio",
	"ws-tls-tokio",
]
