[package]
name = "sandwitch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1" }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
futures = { version = "0.3" }
web3 = { version = "0.18", default-features = false, features = ["ws-tokio", "ws-tls-tokio"] }
ethabi = { version = "17.1" }
hex = { version = "0.4" }
lazy_static = { version = "1.4" }
toml = { version = "0.5" }
serde = { version = "1", features = ["derive"] }
clap = { version = "3.2", features = ["derive"] }
