services:
  sandwitch:
    build: .
    command:
      - '-vv' # info log level
    stop_signal: SIGINT
    stop_grace_period: '30s'
    healthcheck:
      disable: true

  prometheus:
    image: 'prom/prometheus:latest'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=warn'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml:ro'
    ports:
      - '9090:9090/tcp'
    depends_on:
      - sandwitch
    restart: unless-stopped

  grafana:
    image: 'grafana/grafana-oss:latest'
    volumes:
      - './grafana.ini:/etc/grafana/grafana.ini:ro'
      - './grafana/datasources/:/etc/grafana/provisioning/datasources/:ro'
      - './grafana/dashboards/:/etc/grafana/provisioning/dashboards/:ro'
    depends_on:
      - prometheus
    ports:
      - '3000:3000/tcp'
