global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sandwitch'
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: '/metrics'
    scheme: http
    static_configs:
      - targets: ['sandwitch:9000']
