[package]
name = "sandwitch-monitor-logger"
version.workspace = true
edition.workspace = true

[dependencies]
sandwitch-engine.workspace = true

anyhow.workspace = true
futures.workspace = true
tracing.workspace = true
