[package]
name = "pancake_toaster_contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { workspace = true, features = ["abigen"] }

[build-dependencies]
bindgen = { workspace = true }
