{
 "title": "Sandwitch",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"sandwitch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sandwitch_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1/irate(sandwitch_height[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "tx/s" } },
   "targets": [
    {
     "expr": "irate(sandwitch_seen_txs[$__rate_interval])",
     "legendFormat": "Seen"
    },
    {
     "expr": "irate(sandwitch_resolved_txs[$__rate_interval])",
     "legendFormat": "Resolved"
    },
    { "expr": "sandwitch_buffered_txs", "legendFormat": "Buffered" },
    {
     "expr": "irate(sandwitch_pancake_swap_to_router[$__rate_interval])",
     "legendFormat": "PancakeSwap Router"
    }
   ]
  },
  {
   "title": "Total Resolved TX",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sandwitch_resolved_txs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Resolve TX Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sandwitch_resolved_txs / sandwitch_seen_txs",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pancake Swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pancake Swap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sandwitch_pancake_swap_pair_hit_times",
     "legendFormat": "{{token0_name}} -> {{token1_name}}"
    }
   ]
  }
 ]
}