[package]
name = "contracts"
version.workspace = true
edition.workspace = true

[dependencies]
ethers = { workspace = true, features = ["abigen"] }

[build-dependencies]
ethers = { workspace = true, features = ["abigen", "ethers-solc"] }

[features]
pancake_swap = []
pancake_toaster = []
