[package]
name = "contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { workspace = true, features = ["abigen"] }

[build-dependencies]
ethers = { workspace = true, features = ["abigen", "ethers-solc"] }

[features]
pancake_swap = []
pancake_toaster = []
